### ISSUE TITLE
DYMO Connect JavaScript SDK link in WPFSDKSample/README.md is broken

### ISSUE THREAD

**Issue by fssup** [dymosoftware/DCD-SDK-Sample#11]
In the [README](https://github.com/dymosoftware/DCD-SDK-Sample/blob/master/WPF/WPFSDKSample/README.md) file there's a link to `DYMO Connect JavaScript SDK`, which points to `http://ddymojavascriptsdk.com/`, which is NXDOMAIN.

**Comment by dymosoftware** [comment]
README file has been updated.

**Comment by markheloking** [comment]
WPFSDKSample/README.md has not yet been updated though, and the mentioned NXDOMAIN link is still there.

**Comment by dymosoftware** [comment]
See follow commit https://github.com/dymosoftware/DCD-SDK-Sample/commit/f023460ade8f2283cb4c0dbff595d25f3a5cb81c

**Comment by markheloking** [comment]
Commit doesn't fix the link under acknowledgement named "DYMO Connect JavaScript SDK"

**Comment by dymosoftware** [comment]
Fixed link in acknowledgement section.
