### ISSUE TITLE
Could not load file or assembly 'DYMOPrinting' or one of its dependencies. An attempt was made to load a program with an incorrect format.

### ISSUE THREAD

**Issue by JagadishaBS** [dymosoftware/DCD-SDK-Sample#13]
I am trying to implement the same solution in MVC application and added the DLL via Nuget package and I am able to build the application but once run the application locally I am getting the error below error 
![image](https://user-images.githubusercontent.com/9428654/87646538-99443180-c76c-11ea-82c9-bc63133ba321.png)

![image](https://user-images.githubusercontent.com/9428654/87647514-05bf3080-c76d-11ea-9e47-7d52f11bf7f7.png)

is this DLL support in MVC application.

Target framework .NET Framework 4.6.1.

**Comment by victornamuso** [comment]
@JagadishaBS @vmark99 did you find a resolution for this?
