### ISSUE TITLE
Dymo 450 on Apple Airport

### ISSUE THREAD

**Issue by MartinMIL** [dymosoftware/DCD-SDK-Sample#14]
Hi, I am just a user with no programming experience. We run Dymo 400 and 450 printers on an Apple Airport Network device for years. No problem with Mac computers.

But now I have to install the Dymo printer and Dymo Connect software on Win 10 computers.

First, I install Bonjour Printer service which finds the Dymo printer in the list.
But then Bonjour asks for a driver - and I can't find a simple Dymo driver for Win 10.
Could anyone help me on that?

Regards, Martin

![bonjour_dymodriver_needed](https://user-images.githubusercontent.com/69307157/89549250-6095f600-d808-11ea-90ac-b7ff80ea50bf.PNG)

**Comment by dymosoftware** [comment]
@MartinMIL please send your concern to SDKReply@newellco.com, our Consumer Care team will help you.
