### ISSUE TITLE
Printing Label with image

### ISSUE THREAD

**Issue by LINOHWANG** [dymosoftware/DCD-SDK-Sample#15]
C# POS Application Integrated with Dymo 450 Label Writer Turbo using SDK,
Found problems printing with a image.

450 Turbo is making weird sound when trying to print 1st label and feeding backwards a bit, if label contain an image.

Without an image on label, it is doing backwards a little bit, but printing is correctly performed on every labels.

Image file size that I used was just 44kb and Dymo file size was 14kb.

Let me know if you have any fix for this.

**Comment by dymosoftware** [comment]
Hi @LINOHWANG , it seems to be a hardware issue. You can contact [dymoconsumercare@newellco.com](url).
