### ISSUE TITLE
Feature Request: Serial Number of Printer

### ISSUE THREAD

**Issue by stormframe** [dymosoftware/DCD-SDK-Sample#17]
Hello developer team,
would it be possible to read out the serial number or a unique identifier of the printer using the JS Framework?

Thus different labels could be inserted in 2 or 3 printers. The correct printer is activated using the serial number.

**Comment by dymosoftware** [comment]
Issue duplicated. See [DYMO Connect Framework #9](https://github.com/dymosoftware/dymo-connect-framework/issues/9).
