### ISSUE TITLE
PreviewAndPrintLabel sample does not work

### ISSUE THREAD

**Issue by theOzzieRat** [dymosoftware/DCD-SDK-Sample#2]
I downloaded the Javascript samples to test and it does not work for me. Using the PreviewAndPrintLabel sample, when I choose the .dymo or .label file in the example directory I just get an error message saying "The file is not a valid label". The file opens just fine in Dymo Connect. This is using Chrome on Windows 10 Pro (everything the latest version).

**Comment by dymosoftware** [comment]
Hi @theOzzieRat, what are the files that you are trying to open? Have you tried to open the file without our sample? PreviewAndPrintLabel validate label structure and address object.

**Comment by theOzzieRat** [comment]
It won't open any .dymo or .label file. The one in the sample directory included.
[https://github.com/dymosoftware/DCD-SDK-Sample/blob/master/JavaScript/PreviewAndPrintLabel/PreviewLabelFramework.dymo](url)

**Comment by smehtaCAS** [comment]
+1 Same here. 
The isValidLabel() method returns true. 
I am not using any Params. So it is an empty XML. I tried with passing empty string for printerName. 

I get error code 500 from the Web service.

**Comment by dymosoftware** [comment]
@theOzzieRat  Some browsers don't return the full path to be able to open the label file. You can download and update the specific path in the sample.

**Comment by dymosoftware** [comment]
> +1 Same here.
> The isValidLabel() method returns true.
> I am not using any Params. So it is an empty XML. I tried with passing empty string for printerName.
> 
> I get error code 500 from the Web service.

Could you provide more details about isValidLabel returning true?
Web service returns this error since printer name is not found.
