### ISSUE TITLE
Problem with preview

### ISSUE THREAD

**Issue by klebk** [dymosoftware/DCD-SDK-Sample#26]
Hi, I'm testing this code PreviewAndPrintLabel.html, I didn't touch it, just run it.
And I can't figure out what I'm doing wrong, is maybe some setting on Dymo side?
(It's used default XML, because it refuse to load XML from file).

I get always space at beginning of second and third line.
![space_at_beginning](https://user-images.githubusercontent.com/66938753/114036433-5c7f1400-9880-11eb-97ee-b1e854893be5.JPG)

If I want four lines of text it get completely mixed address ... I also tried to modify text size to 8 and still same mixing ... 
![image](https://user-images.githubusercontent.com/66938753/114036362-4d986180-9880-11eb-9456-41d4399ac5c8.png)

Thank you for your help.
Best regards,
Klemen

**Comment by klebk** [comment]
Well, I noticed that I don't have last Dymo Connect and Dymo Label ... so I updated to version DCD 1.3.2.18 and DLS 8.7.4.
And now I get message "No DYMO printers are installed. Install DYMO printers."

In both software I'm able to print, but through JavaScript code I can't.

![image](https://user-images.githubusercontent.com/66938753/114044735-c222ce80-9887-11eb-8a27-1113517379d1.png)

**Comment by dymosoftware** [comment]
> Hi, I'm testing this code PreviewAndPrintLabel.html, I didn't touch it, just run it.
> And I can't figure out what I'm doing wrong, is maybe some setting on Dymo side?
> (It's used default XML, because it refuse to load XML from file).
> 
> I get always space at beginning of second and third line.
> ![space_at_beginning](https://user-images.githubusercontent.com/66938753/114036433-5c7f1400-9880-11eb-97ee-b1e854893be5.JPG)
> 
> If I want four lines of text it get completely mixed address ... I also tried to modify text size to 8 and still same mixing ...
> ![image](https://user-images.githubusercontent.com/66938753/114036362-4d986180-9880-11eb-9456-41d4399ac5c8.png)
> 
> Thank you for your help.
> Best regards,
> Klemen

Hi @klebk , which DYMO webservice/software is running on your machine? DYMO Connect or DLS? If you open the same label with DYMO Software do you get same issue? If you print the label do you see the same space at the left?

**Comment by klebk** [comment]
Hi @dymosoftware , I didn't know it's possible also with DYMO Label to have web service. I had problems with Connect, when I installed DLS and disable Connect web service it started work normal!
Thanks for help!
