### ISSUE TITLE
DymoLabel constructor error with version 1.4.2.19 nupkg

### ISSUE THREAD

**Issue by owentlarkin** [dymosoftware/DCD-SDK-Sample#32]
I am trying to build DYMOConnectSampleWPF in visualstudio 2019. I have done this in the past. The DYMO.Connect.SDK package was updated to version 1.4.2.19 and i am getting an error.

![Screenshot - 9_16_2021 , 9_56_05 AM](https://user-images.githubusercontent.com/12503824/133626674-e70f341a-8048-4dbf-8ce0-e6bd71174410.png)

I can't find any documentatio or example for the constructor.

**Comment by dymosoftware** [comment]
> I am trying to build DYMOConnectSampleWPF in visualstudio 2019. I have done this in the past. The DYMO.Connect.SDK package was updated to version 1.4.2.19 and i am getting an error.
> 
> ![Screenshot - 9_16_2021 , 9_56_05 AM](https://user-images.githubusercontent.com/12503824/133626674-e70f341a-8048-4dbf-8ce0-e6bd71174410.png)
> 
> I can't find any documentatio or example for the constructor.

Sample updated to version 1.4.2.20 of DYMO.Connect.SDK.

**Comment by Forbearance** [comment]
It seems that DymoLabel class was updated to use a Singleton design pattern, so you will need to modify the code to get the Instance prop.
