### ISSUE TITLE
Need LabelSet Example

### ISSUE THREAD

**Issue by brianedelman** [dymosoftware/DCD-SDK-Sample#35]
A LabelSet example would be amazing

**Comment by buruhazard** [comment]
LabelSet of what? You talking about UpdateLabelObject()? This issues is only for DYMO.Connect.SDK

**Comment by brianedelman** [comment]
You are right. I'll close this issue. Unfortunately the dymo eco system isn't super well documented so I was lost in the maze that is dymo at the time I wrote this.
