### ISSUE TITLE
Erstellen einer VB.NET Forms App, zum drucken eines Etiketts mit einem Dymo-Label Writer mit dem NuGet-Packet Dymo.Connect.SDK 

### ISSUE THREAD

**Issue by Sini1504** [dymosoftware/DCD-SDK-Sample#46]
Hallo, ich habe leider einige Probleme, das NuGet-Packet zu nutzen.
Ich habe ein neues Projekt angelegt und das NuGet-Packet "Dymo.Connect.SDK" heruntergeladen.

Zu aller erst importierte ich `DymoSDK.Implementations`.

Hier weiter mein Code:
`
    
    Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click

        Dim dymoSDKLabel As DymoSDK.Implementations.DymoLabel

        DymoSDK.App.Init()

        Dim SelectedPrinter As String = "DYMO LabelWriter 450"

        Dim copies As Integer = 1

        Dim barcodeGraphsQuality As Boolean = True

        'dymoSDKLabel = New DymoLabel()

        dymoSDKLabel = DymoLabel.Instance

        dymoSDKLabel.LoadLabelFromFilePath("R:\Produktion\Praktikanten\OFE\test.dymo")

        DymoPrinter.Instance.PrintLabel(dymoSDKLabel, SelectedPrinter, copies, barcodeGraphsQuality)

    End Sub
`

Ich habe den Punkt `dymoSDKLabel = new DymoLabel()` auskommentiert, da ein Überladungsfehler auftritt, weshalb ich 
 `dymoSDKLabel = DymoLabel.Instance` eingebaut habe. 

Mein Label enthält eine Textbox, da ich nur einmal Testen wollte, wie alles funktioniert. Erstellt mit der Dymo Connect Software.

Nach dem Button-Klick passiert aber nichts. Ich bekomme keine Fehlermeldung oder sonstiges.

Nur die Nachricht im Ausgabefenster:
![image](https://user-images.githubusercontent.com/100778956/156373905-f941c2a4-7ba7-44e0-a080-21034ea03b73.png)

Kann mir jemand weiterhelfen oder einfach mal ein Code-Beispiel hochladen?

Meine erzeugten Label mit der Dymo Label Software habe ich mit VB.NET und dem Dymo.Framework immer bearbeitet und gedruckt. Nun wollte ich auch ein neues System umsteigen und kapiere das ganze noch nicht wirklich.

**Comment by skillsinc-Ed** [comment]
It looks correct to me.
I have a sample vb.net application that I shared on GitHub if you want to look at the code:
https://github.com/skills-inc/Dymo-Connect-SDK-Sample-Application-for-VB.net

**Comment by Sini1504** [comment]
It seems like not all DLLs are installed properly. Thank you for your answer!
