### ISSUE TITLE
DYMO.Label - COM not found

### ISSUE THREAD

**Issue by pburczyn** [dymosoftware/DCD-SDK-Sample#5]
Hello

Your new nuget package requires .NET Framework 4.6.1. But I have to support application with .NET Framework 4.0

I install yor older nuget package: DYMO.Label https://www.nuget.org/packages/DYMO.Label 
but i get an error: System.Runtime.InteropServices.COMException
COM not found CLSID {E8D851FA-9967-4ADF-9644-0183B9B1EA68}

Could you please help me?

**Comment by dymosoftware** [comment]
Hi @pburczyn , DYMO.Label is not an official nuget package. Old SDK could be helpful https://www.dymo.com/en-US/online-support/online-support-sdk
