### ISSUE TITLE
NullReferenceException when retrieving printers

### ISSUE THREAD

**Issue by jonokie** [dymosoftware/DCD-SDK-Sample#63]
I am getting a NullReferenceExeption when calling the following:
DymoSDK.Implementations.DymoPrinter.Instance.GetPrinters();

Here's the call stack:
    DYMO.LabelAPI.Windows.Printers.SpoolerMonitorGateway.SpoolerMonitorGateway()
    DYMO.LabelAPI.Windows.PrinterDiscovery.WindowsDeviceDiscoveryAgent.WindowsDeviceDiscoveryAgent()

**Comment by jonokie** [comment]
Never mind. There were files missing in the compile-to folder.

**Comment by ksladowski** [comment]
What files were missing? I've added every dll I could find in the package and still happening.

**Comment by jonokie** [comment]
I do not remember specific files that were missing. I removed all references to Dymo, cleaned my solution, and re-added the references. After that, I had to go through their package folders and hand-pick files to copy to my target folder.

**Comment by ksladowski** [comment]
Any chance you could show me the reference list for the project? I've removed all Dymo references and restarted this process twice now

![image](https://user-images.githubusercontent.com/53124911/183748970-70cddc4e-16c9-4cf5-81c5-dcacd1eed52a.png)

**Comment by jonokie** [comment]
![image](https://user-images.githubusercontent.com/2934620/183750557-56f57211-be8e-490c-b106-473fdeec1cfb.png)

Target folder:
![image](https://user-images.githubusercontent.com/2934620/183750795-e4a6755e-8a8c-4a47-8915-5b3ad58c83b7.png)

**Comment by jonokie** [comment]
I would check to make sure the platform-specific files you have referenced and/or copied into your bin folder match your project's platform setting. If you are targeting "AnyCPU", try changing that to "x86" (or vice-versa) and see if it works. If it does, that tells you have 32-bit dependencies even through you are targeting 64-bit (or vice versa).
